language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
  global:
    - TERM=dumb

android:
  components:
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - android-19
    - android-23
    - sys-img-armeabi-v7a-android-19

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  - cd AndroidTestingBlueprint

before_cache:
  - rm -f AndroidTestingBlueprint/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - AndroidTestingBlueprint/.gradle/caches/
    - AndroidTestingBlueprint/.gradle/wrapper/

script: 
  - ./gradlew assembleDebug
  - ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.android.testing.blueprint.integration.OkTest
